### ISSUE TITLE
Get an API from the steam server

### ISSUE THREAD

**Issue by talentdev0314** [talentdev0314/repo#2]
How can I get an API from the steam server? Please help with me.

**Comment by wonderdev007** [comment]
This is a API doc what I have used..
https://shockbyte.com/billing/knowledgebase/350/How-to-Get-a-Steam-Web-API-Key-for-Your-CSGO-Server.html

**Comment by talentdev0314** [comment]
That works!

**Comment by wonderdev007** [comment]
At first, you have to get an ID from the steam server.
1.Go to the Google Maps Platform > Credentials page. Go to the Credentials page.
2.On the Credentials page, click Create credentials > API key. The API key created dialog displays your newly created API key.
3.Click Close. The new API key is listed on the Credentials page under API keys.

**Comment by wonderdev007** [comment]
At first, you have get a steam ID.

**Comment by wonderdev007** [comment]
> How can I get an API from the steam server? Please help with me.

This is a API doc what I have used..
https://shockbyte.com/billing/knowledgebase/350/How-to-Get-a-Steam-Web-API-Key-for-Your-CSGO-Server.html
